# .travis.yml

language: php

php:
  - 5.6

before_script:
  - composer install --dev

script:
  - phpunit --bootstrap vendor/autoload.php --coverage-clover=coverage.clover tests

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
